import 'dart:convert';

import 'package:flutter/services.dart';

import 'format.dart';
import 'models.dart';

/// Residential targeting catalog: countries → states → cities, with the ISPs
/// available at each level. Generated by tool/build_geo_catalog.py from the
/// authorized catalog input weights.json; it holds names only (every place and ISP
/// with at least 25 live IPs), never counts. States, cities and ISPs come
/// ordered by live IPs, most first; countries are A–Z.
class GeoCatalog {
  GeoCatalog._(this.countries, this._regions, this._cities, this._isps, this._index);

  final List<GeoCountry> countries;
  final Map<String, List<GeoRegion>> _regions; // cc
  final Map<String, List<GeoCity>> _cities; // cc → all cities (regionSlug set)
  final Map<String, List<GeoAsn>> _isps; // "cc", "cc/region", "cc/region/city"
  final List<_Entry> _index;

  static GeoCatalog? _instance;
  static Future<GeoCatalog>? _loading;

  /// Loaded catalog, or null before [load] finishes.
  static GeoCatalog? get instance => _instance;

  static Future<GeoCatalog> load() =>
      _loading ??= rootBundle.loadString('assets/geo/catalog.json').then((s) => _instance = _parse(jsonDecode(s) as Map<String, dynamic>));

  static GeoCatalog _parse(Map<String, dynamic> json) {
    final names = (json['isps'] as Map<String, dynamic>).map((k, v) => MapEntry(int.parse(k), v as String));
    final asnCache = <int, GeoAsn>{};
    List<GeoAsn> isps(List<dynamic> list) => [for (final n in list.cast<int>()) asnCache[n] ??= GeoAsn(n, names[n] ?? 'AS$n')];

    final countries = <GeoCountry>[];
    final regions = <String, List<GeoRegion>>{};
    final cities = <String, List<GeoCity>>{};
    final ispMap = <String, List<GeoAsn>>{};
    final index = <_Entry>[];

    for (final c in (json['countries'] as List).cast<Map<String, dynamic>>()) {
      final country = GeoCountry(c['code'] as String, c['name'] as String);
      countries.add(country);
      index.add(_Entry(country.name, GeoSearchResult(GeoHitKind.country, country)));
      final countryIsps = isps(c['isps'] as List);
      ispMap[country.code] = countryIsps;
      for (final a in countryIsps) {
        index.add(_Entry(a.name, GeoSearchResult(GeoHitKind.asn, country, asn: a), alt: 'as${a.asn}'));
      }
      final rs = <GeoRegion>[];
      final byRegion = <List<GeoCity>>[];
      for (final r in (c['regions'] as List).cast<Map<String, dynamic>>()) {
        final region = GeoRegion(slugify(r['name'] as String), r['name'] as String);
        rs.add(region);
        final regionCities = <GeoCity>[];
        byRegion.add(regionCities);
        index.add(_Entry(region.name, GeoSearchResult(GeoHitKind.region, country, region: region)));
        ispMap['${country.code}/${region.slug}'] = isps(r['isps'] as List);
        for (final ci in (r['cities'] as List).cast<Map<String, dynamic>>()) {
          final city = GeoCity(slugify(ci['name'] as String), ci['name'] as String, regionSlug: region.slug);
          regionCities.add(city);
          index.add(_Entry(city.name, GeoSearchResult(GeoHitKind.city, country, region: region, city: city)));
          ispMap['${country.code}/${region.slug}/${city.slug}'] = isps(ci['isps'] as List);
        }
      }
      regions[country.code] = rs;
      // Country-wide city list in live-IP order: [regionIndex, cityIndex] pairs.
      cities[country.code] = [
        for (final pos in (c['cityRank'] as List).cast<List<dynamic>>()) byRegion[pos[0] as int][pos[1] as int],
      ];
    }
    return GeoCatalog._(countries, regions, cities, ispMap, index);
  }

  List<GeoRegion> regions(String cc) => _regions[cc] ?? const [];

  List<GeoCity> cities(String cc, {String? region}) {
    final all = _cities[cc] ?? const <GeoCity>[];
    return region == null ? all : all.where((c) => c.regionSlug == region).toList();
  }

  /// ISPs with enough IPs at the most specific level given.
  List<GeoAsn> isps(String cc, {String? region, String? city}) {
    final key = [cc, ?region, if (region != null) ?city].join('/');
    return _isps[key] ?? const [];
  }

  /// Search countries, states, cities and ISPs at once. Prefix matches rank
  /// above substring matches; places above ISPs.
  List<GeoSearchResult> search(String query, {int limit = 50}) {
    final q = query.trim().toLowerCase();
    if (q.isEmpty) return const [];
    final asNumber = RegExp(r'^(as)?\d+$').hasMatch(q) ? 'as${q.replaceFirst('as', '')}' : null;
    final buckets = List.generate(8, (_) => <GeoSearchResult>[]);
    for (final e in _index) {
      final kindRank = e.hit.kind.index; // country, region, city, asn
      if (asNumber != null && e.alt != null && e.alt!.startsWith(asNumber)) {
        buckets[3].add(e.hit);
      } else if (e.lower.startsWith(q)) {
        buckets[kindRank].add(e.hit);
      } else if (e.lower.contains(q)) {
        buckets[4 + kindRank].add(e.hit);
      }
    }
    return [for (final b in buckets) ...b].take(limit).toList();
  }
}

class _Entry {
  _Entry(String name, this.hit, {this.alt}) : lower = name.toLowerCase();
  final String lower;
  final GeoSearchResult hit;
  final String? alt;
}
